# Generated by Django 4.2 on 2023-05-03 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('ApplicantID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('StatusID', models.AutoField(primary_key=True, serialize=False)),
                ('StatusName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('EmployerID', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=255)),
                ('Industry', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('JobID', models.AutoField(primary_key=True, serialize=False)),
                ('JobTitle', models.CharField(max_length=255)),
                ('JobDescription', models.TextField(blank=True, null=True)),
                ('Salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Location', models.CharField(blank=True, max_length=255, null=True)),
                ('DatePosted', models.DateField()),
                ('EmployerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('ApplicationID', models.AutoField(primary_key=True, serialize=False)),
                ('DateApplied', models.DateField()),
                ('ApplicantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.applicant')),
                ('JobID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.job')),
                ('StatusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.applicationstatus')),
            ],
        ),
    ]
