# Generated by Django 4.2 on 2023-05-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPost',
        ),
        migrations.RenameField(
            model_name='applicationstatus',
            old_name='StatusID',
            new_name='id',
        ),
        migrations.AddField(
            model_name='employer',
            name='is_employer',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='StatusName',
            field=models.CharField(choices=[('Interested', 'Interested'), ('In Review', 'In Review'), ('Accepted', 'Accepted'), ('Dormant', 'Dormant'), ('Declined', 'Declined')], max_length=255),
        ),
    ]
