# Generated by Django 4.1.7 on 2023-05-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_employer_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
