# Generated by Django 4.2 on 2023-05-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_applicant_is_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatus',
            name='StatusName',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
