# Generated by Django 4.2 on 2023-05-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_alter_applicationstatus_statusname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='DatePosted',
            field=models.DateField(verbose_name='Date Posted'),
        ),
        migrations.AlterField(
            model_name='job',
            name='JobDescription',
            field=models.TextField(blank=True, null=True, verbose_name='Job Description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='JobTitle',
            field=models.CharField(max_length=255, verbose_name='Job Title'),
        ),
    ]
